### ISSUE TITLE
[Feature] 请问有计划支持Apple Silicon的模拟器吗？

### ISSUE THREAD

**Issue by 0xBa0** [bytedance/Bytedance-UnionAD#144]
如图，版本是3.7.0.8，模拟器是iPhone 12mini

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/39689377/126603233-0e2e966b-ad21-4f11-ace9-e3ccbe89b02b.png">

**Comment by liubo-ddk** [comment]
请尝试参考：[这里](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io)

**Comment by liubo-ddk** [comment]
We released 4.1.0.2 version to enhanced compatibility with Silicon Chips.
Please try update SDK version should fix some error case.

**Comment by ikesyo** [comment]
https://github.com/bytedance/Bytedance-UnionAD/blob/4.1.0.2/Ads-Global/Ads-Global.podspec

It looks like v4.1.0.2 doesn't use xcframeworks yet. To support arm64 simulator on Apple Silicon Macs, xcframeworks must be used over traditional frameworks.

ref: https://onesignal.com/blog/xcframeworks-guide/

**Comment by ddaddy** [comment]
Yes please distribute `.xcframework`'s as I can't use this on my M1 Mac.

**Comment by ikesyo** [comment]
This is not resolved yet, traditional `*.framework`s are still used thus arm64 simulator is not supported.
